global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: your-app-label

  - job_name: 'example-app'
    static_configs:
      - targets: ['example-app-1:8080', 'example-app-2:8080']
        labels:
          instance: example-app-1
          app: your-app-label

      - targets: ['example-app-3:8080', 'example-app-4:8080']
        labels:
          instance: example-app-2
          app: your-app-label
